### ISSUE TITLE
Protobuf-Message build fail

### ISSUE THREAD

**Issue by ethflo** [robocup-logistics/rcll-refbox#31] opened 2019-05-18 07:10 UTC
Hi all refbox devops,

to update the logistics league visualization for this years robocup I tried to install the refbox in a VM and had some issues with compiling the protobuf messages:
When compiling the refbox, the build of the protobuf messages fails at MachineInstructions.proto line 64/65. Here the qualifier "reserved" is not accepted, just the qualifiers "required", "optional" and "repeated". 
`` 
MachineInstructions.proto:64:3: Expeced "required", "optional", or "repeated".
``
This is followed by some aftereffects.

The changes at this part of code were made by @morxa  just a month ago. As I suggest, that the build succeded at your development, you probably used different dependecies as I. Are there new dependencies, maybe proto3, which would allow this qualifier? If yes, please update the installation guide and move it to this repo, that the teams have a chance to build the updated messages and changed refbox.

My system environment is as follows:
- Virtual Machine, Ubuntu 16.04 (64bit)
- Refbox dependencies installed along [Fawkes Refbox Installation Guide](https://trac.fawkesrobotics.org/wiki/RCLLRefBox/Install); Note: At apt-get dependecies libncurses5-dev or similar is missing
- master branch of this repo

Thanks for your help!

Best regards
Florian

**Comment by morxa** [comment] 2019-05-18 08:32
Yes, you need protobuf3. Why are you using Ubuntu 16.04? Even if you use Ubuntu LTS, there is a newer release.

We use Ubuntu Bionic (the latest LTS release) for testing Ubuntu builds, see e.g., the [latest build](https://circleci.com/gh/robocup-logistics/rcll-refbox/156). 

The most up-to-date source for build dependencies is the circleci config:
https://github.com/robocup-logistics/rcll-refbox/blob/a02529aa42f5c79756a3633eaf41cc60327037d3/.circleci/config.yml#L32-L64

That being said, you can get rid of the protobuf3 dependency simply by removing the lines using the reserved qualifier. The generated messages will be compatible as long as you don't re-use the slot ID of the reserved fields. I would still recommend using Ubuntu Bionic or later.

Apologies for not keeping the wiki up-to-date.

**Comment by morxa** [comment] 2019-05-18 08:37
As this boils down to the wiki not being up-to-date, I'm closing this as duplicate of #3. Feel free to re-open if there are other issues.

**Closed** 2019-05-18 08:37 UTC

**Comment by ethflo** [comment] 2019-05-18 10:50
Thanks for the quick answer!

As far I see there are two options:
- As the MachineInstructions.proto file has now proto3 syntax, line 37 should be adjusted respectively to make this clear. Stating there proto2 as used syntax but in fact needing proto3 (also if it works for you with the proto2 statement) is not consistent and leads to confusions.
- I fear, that teams, which have no or just few experience with protobuf, might not dare to modify the .proto files as long there is no explicit information. There could be a explicit hint to comment the lines for proto2 users. Alternatively the "reserved" lines can directly be commented to inform that the field id's shouldn't be reused because of backward compatibility.

Do I understand you correctly: proto3 is a required dependency for the file, but this does not require necessarily ubuntu18.04 (through its recommended)? Not everyone works with the newest ubuntu, as there are often issues with not yet compatible / not yet updated / not yet migrated other software.

Thank you for the help!
Florian

**Comment by morxa** [comment] 2019-05-18 11:49
> Thanks for the quick answer!
> 
> As far I see there are two options:
> 
>     * As the MachineInstructions.proto file has now proto3 syntax, line 37 should be adjusted respectively to make this clear. Stating there proto2 as used syntax but in fact needing proto3 (also if it works for you with the proto2 statement) is not consistent and leads to confusions.

I stand corrected: `reserved` is already a keyword in protobuf2: https://developers.google.com/protocol-buffers/docs/proto#reserved
I assume (without any further research) that Ubuntu 16.04 simply ships a protobuf compiler that is too old.

> 
>     * I fear, that teams, which have no or just few experience with protobuf, might not dare to modify the .proto files as long there is no explicit information. There could be a explicit hint to comment the lines for proto2 users. Alternatively the "reserved" lines can directly be commented to inform that the field id's shouldn't be reused because of backward compatibility.

This is exactly what `reserved` is used for and directly specified in the protobuf language specs. I don't think adding a comment would be helpful because it would not contain any additional information. 

I thought about merely dropping the field, but this would have the disadvantage that teams who forgot to switch to sending the order ID would send messages in the correct format but with the wrong payload, which would be much more difficult to debug than a direct message that the message format is incompatible (that's the reason why the `reserved` keyword was introduced).
> 
> 
> Do I understand you correctly: proto3 is a required dependency for the file, but this does not require necessarily ubuntu18.04 (through its recommended)? Not everyone works with the newest ubuntu, as there are often issues with not yet compatible / not yet updated / not yet migrated other software.

Well, I'm not responsible for everyone's tech stack. I'm not asking anyone to work with the the latest Ubuntu, but if you decide to use a release that's over three years old, that's your choice. We develop for Fedora and fully support the latest Fedora release. We also try to support the latest Ubuntu LTS. This is why you can find both of these in the CI tools.

Of course we always accept PRs that make the refbox compatible with older releases (assuming such a PR does not ship a lot of technical debt), but I can't possibly test and support 4 different releases (that's the number of Ubuntu releases since 16.04) of a distribution that I don't use at all.

**Comment by morxa** [comment] 2019-05-18 13:31
FTR: We've moved the wiki away from Fawkes Trac to a [GitHub Wiki](https://github.com/robocup-logistics/rcll-refbox/wiki). It's not updated either, but should be used as future source for information. I've added that information to the Trac pages, but missed the installation sub-page.
